import SignInButton from "@/components/SignInButton";
import GuestTestButton from '@/components/GuestTestButton';
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { Brain, Lightbulb, Timer, Trophy } from "lucide-react";

export default async function Home() {
  const currentYear = new Date().getFullYear();
  const session = await getServerSession();
  if (session?.user) {
    redirect("/dashboard");
  }

  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-b from-background to-secondary/10">
      {/* Hero Section */}
      <div className="relative w-full flex flex-col items-center justify-center py-20 px-4">
        <div className="absolute inset-0 bg-grid-white/10 bg-grid-16 [mask-image:radial-gradient(white,transparent_85%)]" />
        
        <div className="text-center space-y-4 relative z-10 mb-12">
          <h1 className="text-4xl md:text-6xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60">
            Welcome to Quizify
          </h1>
          <p className="text-xl md:text-2xl text-muted-foreground max-w-2xl mx-auto">
            Test your knowledge with AI-powered quizzes on any topic
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto mb-12">
          {[
            {
              icon: Brain,
              title: "AI-Powered",
              description: "Smart questions generated by AI"
            },
            {
              icon: Timer,
              title: "Quick & Easy",
              description: "Take quizzes in minutes"
            },
            {
              icon: Trophy,
              title: "Track Progress",
              description: "Monitor your improvement"
            },
            {
              icon: Lightbulb,
              title: "Any Topic",
              description: "Learn about anything"
            }
          ].map((feature, index) => (
            <div
              key={index}
              className="flex flex-col items-center text-center p-6 rounded-xl bg-card border shadow-sm hover:shadow-md transition-shadow"
            >
              <feature.icon className="w-12 h-12 mb-4 text-primary" />
              <h3 className="font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>

        {/* Auth Card */}
        <div className="relative w-full max-w-md mx-auto">
          <div className="absolute inset-0 bg-gradient-to-r from-primary/20 to-secondary/20 transform rotate-1 rounded-2xl blur-2xl" />
          <div className="relative bg-card border rounded-xl shadow-xl p-8 backdrop-blur-sm">
            <div className="space-y-8">
              <div className="text-center space-y-2">
                <h2 className="text-2xl font-bold tracking-tight">Start Your Learning Journey</h2>
                <p className="text-muted-foreground text-sm">
                  Create an account to save progress and track your learning
                </p>
              </div>

              <div className="space-y-6">
                <SignInButton />
                
                <div className="flex items-center gap-2">
                  <div className="h-px flex-1 bg-border" />
                  <span className="text-xs text-muted-foreground font-medium">OR</span>
                  <div className="h-px flex-1 bg-border" />
                </div>

                <GuestTestButton />
              </div>

              <div className="text-center">
                <p className="text-xs text-muted-foreground">
                  By continuing, you agree to our{" "}
                  <a href="#" className="underline hover:text-primary">Terms of Service</a>
                  {" "}and{" "}
                  <a href="#" className="underline hover:text-primary">Privacy Policy</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="w-full py-6 text-center text-sm text-muted-foreground">
        <p>© {currentYear} Quizify. All rights reserved.</p>
        <p>Created by Ashwani Paras</p>
      </footer>
    </main>
  );
}
